# Generated by Django 4.0.2 on 2022-02-10 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_rename_body_news_content_news_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.news')),
            ],
        ),
    ]
