# Generated by Django 4.0.2 on 2022-02-11 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_remove_mainnews_new_mainnews_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_highlighted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='news',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
