# Generated by Django 4.0.2 on 2022-02-14 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_delete_mainnews'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'News'},
        ),
        migrations.AddField(
            model_name='tag',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
