# Generated by Django 4.0.2 on 2022-02-14 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_alter_news_options_tag_title_en'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='title_en',
        ),
        migrations.AddField(
            model_name='category',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
