# Generated by Django 3.2.13 on 2022-04-26 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_auto_20220426_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
