# Generated by Django 3.2.13 on 2022-04-26 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_alter_news_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
