# Generated by Django 3.2.13 on 2022-05-11 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0016_alter_news_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, upload_to='2022/05/11'),
        ),
        migrations.AlterField(
            model_name='news',
            name='published_at',
            field=models.DateTimeField(),
        ),
    ]
